{{ if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "microsite.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | indent 4 }}

spec:
  rules:
  {{- $root := . -}}
  {{ range $i, $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "microsite.fullname" $root }}
          servicePort: 80
  {{ end }}

{{ if .Values.ingress.tls }}
  tls:
{{ range $i, $tls := .Values.ingress.tls }}
{{ $tls | indent 2 }}
{{ end }}
{{ end }}
{{ end }}
