kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "microsite.fullname" . }}
  labels:
    app: {{ template "microsite.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
  {{ if .Values.persistence.keep }}
    helm.sh/resource-policy: keep
  {{ end }}
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
