{{- if .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microsite.fullname" . }}-tls
  labels:
    app: "{{ template "microsite.fullname" $ }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.keepSecrets }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.certificate | b64enc }}
  tls.key: {{ .Values.ingress.tls.key | b64enc }}
{{- end }}