apiVersion: v1
kind: Secret
metadata:
  name: {{ template "microsite.fullname" . }}
  labels:
    app: {{ template "microsite.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.keepSecrets }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: Opaque
data:
  sftp-user: {{ .Values.sftp.user | b64enc | quote }}
  sftp-password: {{ .Values.sftp.password | b64enc | quote }}
