apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: microsites.microsite-operator.misterjoshua.github.com
spec:
  group: microsite-operator.misterjoshua.github.com
  names:
    kind: MicroSite
    listKind: MicroSiteList
    plural: microsites
    singular: microsite
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
