apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsite-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: microsite-operator
  template:
    metadata:
      labels:
        name: microsite-operator
    spec:
      serviceAccountName: microsite-operator
      containers:
        - name: microsite-operator
          image: wheatstalk/microsite-operator:0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "microsite-operator"
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 32Mi
