init:
  resources: false

resources:
  requests:
    cpu: 1m
    memory: 1Mi
  # limits:
  #   cpu: 1000m
  #   memory: 1024Mi

persistence:
  enabled: true
  keep: false
  accessMode: ReadWriteMany
  size: 5Gi
  storageClass: ""

httpd:
  service:
    type: ClusterIP
    port: 80
  repository: "httpd"
  tag: "2.4-alpine"
  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi

sftp:
  enabled: false
  service:
    type: LoadBalancer
    port: 1022
  repository: "atmoz/sftp"
  tag: "alpine"
  port: 22
  user: user
  password: changeme
  resources: false
  #  requests:
  #    cpu: 1m
  #    memory: 1Mi