init:
  resources: false

resources:
  requests:
    cpu: 500m
    memory: 128Mi

persistence:
  enabled: true
  keep: false
  accessMode: ReadWriteMany
  size: 5Gi
  storageClass: ""

httpd:
  service:
    type: ClusterIP
  image: httpd:2.4-alpine
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits:
      cpu: 500m
      memory: 128Mi

sftp:
  enabled: false
  service:
    type: LoadBalancer
    port: 22
  image: atmoz/sftp:alpine
  port: 22
  user: user
  password: changeme
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits:
      cpu: 500m
      memory: 32Mi

ingress:
  enabled: false
  hosts:
    - example.com
  tls: []
